# Generated by Django 3.0 on 2020-10-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_player_A',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
