# Generated by Django 3.0 on 2020-10-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201009_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='acces_a',
            new_name='access_a',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='acces_b',
            new_name='access_b',
        ),
    ]
