# Generated by Django 3.0 on 2020-10-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201009_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='can_A_play',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='round',
            name='can_B_play',
            field=models.BooleanField(default=True),
        ),
    ]
