# Generated by Django 3.0 on 2020-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201010_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='can_A_play',
        ),
        migrations.RemoveField(
            model_name='round',
            name='can_B_play',
        ),
        migrations.AddField(
            model_name='round',
            name='a_has_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='b_has_played',
            field=models.BooleanField(default=False),
        ),
    ]
